# Nightly Coverage

trigger:
  branches:
    exclude:
    - "*"
pr: none

variables:
  ExternalDataVersion: 1.2.0
jobs:
  - job: LinuxCoverage
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      name: 'Default'
      demands:
      - Agent.OS -equals Linux
    workspace:
      clean: all
    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
      - bash: |
          set -x
          git clone -b dashboard --single-branch ${BUILD_REPOSITORY_URI} SimpleITK-dashboard

          curl -L -O https://github.com/SimpleITK/SimpleITK/releases/download/v$(ExternalDataVersion)/SimpleITKData-$(ExternalDataVersion).tar.gz
          cmake -E tar xfz SimpleITKData-$(ExternalDataVersion).tar.gz
          cmake -E rename SimpleITK-$(ExternalDataVersion)/.ExternalData/MD5 $(Build.SourcesDirectory)/.ExternalData/MD5
        displayName: Download dashboard scripts and testing data
        workingDirectory: $(Agent.BuildDirectory)
      - bash: |
          ctest -S ${BUILD_SOURCESDIRECTORY}/Testing/CI/Azure/azure.cmake
        displayName: Build and test with coverage
        env:
          CCACHE_DISABLE: 1
          CTEST_CONFIGURATION_TYPE: Debug
          CTEST_OUTPUT_ON_FALURE: 1
          CTEST_COVERAGE_COMMAND: /usr/bin/gcov
          CTEST_CACHE: |
              BUILD_DOCUMENTS:BOOL=OFF
              BUILD_EXAMPLES:BOOL=OFF
              BUILD_SHARED_LIBS:BOOL=OFF
              BUILD_TESTING:BOOL=ON
              CMAKE_CXX_FLAGS:STRING=-g -O0 -fprofile-arcs -ftest-coverage
              CMAKE_C_FLAGS:STRING=-g -O0 -fprofile-arcs -ftest-coverage
              CMAKE_EXE_LINKER_FLAGS:STRING=-g -O0 -fprofile-arcs -ftest-coverage
              COVERAGE_COMMAND:PATH=/usr/bin/gcov
              SimpleITK_EXPLICIT_INSTANTIATION:BOOL=OFF
              WRAP_DEFAULT:BOOL=OFF
          DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
          DASHBOARD_DO_COVERAGE: 1
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 1
        workingDirectory: $(Agent.BuildDirectory)
  - job: 'LinuxValgrind'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      name: 'Default'
      demands:
      - Agent.OS -equals Linux
    workspace:
      clean: all
    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
      - script: |
          git clone -b dashboard --single-branch $(Build.Repository.Uri) SimpleITK-dashboard
        displayName: Download dashboard scripts and testing data
        workingDirectory: $(Agent.BuildDirectory)
      - script: |
          [[ ! -z "$(env_file)" ]] && source $(env_file)
          cmake --version
          gcc --version
          ccache -p
          ctest -S "$(Build.SourcesDirectory)/Testing/CI/Azure/azure.cmake" -V
        displayName: Build and test
        env:
          CCACHE_DISABLE: 1
          DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
          DASHBOARD_DO_MEMCHECK: 1
          CTEST_MEMORYCHECK_COMMAND: "/usr/bin/valgrind"
          CTEST_MEMORYCHECK_COMMAND_OPTIONS: "--trace-children=yes --quiet --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --verbose --demangle=yes --gen-suppressions=all  --child-silent-after-fork=yes"
          CTEST_OUTPUT_ON_FALURE: 1
          CTEST_TEST_TIMEOUT: 10000
          CTEST_CONFIGURATION_TYPE: Debug
          CTEST_CACHE: |
            BUILD_SHARED_LIBS:BOOL=ON
            SimpleITK_EXPLICIT_INSTANTIATION:BOOL=OFF
            WRAP_DEFAULT:BOOL=OFF
            BUILD_EXAMPLES:BOOL=ON
            BUILD_SHARED_LIBS:BOOL=OFF
        workingDirectory: $(Agent.BuildDirectory)
