# Nightly Coverage

trigger:
  branches:
    exclude:
    - "*"
pr: none

jobs:
  - job: LinuxCoverage
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      name: 'Default'
      demands:
      - Agent.OS -equals Linux
    workspace:
      clean: all
    steps:
      - template: templates/git-download-steps.yml
      - bash: |
          ctest -D "dashboard_track:STRING=Nightly" -S ${BUILD_SOURCESDIRECTORY}/Testing/CI/Azure/azure.cmake
        displayName: Build and test with coverage
        env:
          CCACHE_DISABLE: 1
          CTEST_CONFIGURATION_TYPE: Debug
          CTEST_OUTPUT_ON_FAILURE: 1
          CTEST_COVERAGE_COMMAND: /usr/bin/gcov
          CTEST_CACHE: |
              BUILD_DOCUMENTS:BOOL=OFF
              BUILD_EXAMPLES:BOOL=OFF
              BUILD_SHARED_LIBS:BOOL=OFF
              BUILD_TESTING:BOOL=ON
              CMAKE_JOB_POOLS:STRING=link=1
              CMAKE_JOB_POOL_LINK:STRING=link
              CMAKE_CXX_FLAGS:STRING=-g -O0 -fprofile-arcs -ftest-coverage
              CMAKE_C_FLAGS:STRING=-g -O0 -fprofile-arcs -ftest-coverage
              CMAKE_EXE_LINKER_FLAGS:STRING=-g -O0 -fprofile-arcs -ftest-coverage
              COVERAGE_COMMAND:PATH=/usr/bin/gcov
              SimpleITK_EXPLICIT_INSTANTIATION:BOOL=OFF
              WRAP_DEFAULT:BOOL=OFF
          DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
          DASHBOARD_DO_COVERAGE: 1
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 1
        workingDirectory: $(Agent.BuildDirectory)
  - job: 'LinuxValgrind'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      name: 'Default'
      demands:
      - Agent.OS -equals Linux
    workspace:
      clean: all
    steps:
      - template: templates/git-download-steps.yml
      - script: |
          [[ ! -z "$(env_file)" ]] && source $(env_file)
          cmake --version
          gcc --version
          ccache -p
          ctest -D "dashboard_track:STRING=Nightly" -S "$(Build.SourcesDirectory)/Testing/CI/Azure/azure.cmake" -V
        displayName: Build and test
        env:
          CCACHE_DISABLE: 1
          DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
          DASHBOARD_DO_MEMCHECK: 1
          CTEST_MEMORYCHECK_COMMAND: "/usr/bin/valgrind"
          CTEST_MEMORYCHECK_COMMAND_OPTIONS: "--trace-children=yes --quiet --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --verbose --demangle=yes --gen-suppressions=all  --child-silent-after-fork=yes"
          CTEST_OUTPUT_ON_FAILURE: 1
          CTEST_TEST_TIMEOUT: 10000
          CTEST_CONFIGURATION_TYPE: Debug
          CTEST_CACHE: |
            BUILD_SHARED_LIBS:BOOL=ON
            SimpleITK_EXPLICIT_INSTANTIATION:BOOL=OFF
            WRAP_DEFAULT:BOOL=OFF
            BUILD_EXAMPLES:BOOL=ON
            BUILD_SHARED_LIBS:BOOL=OFF
        workingDirectory: $(Agent.BuildDirectory)
